# Generated by Django 3.0.7 on 2020-07-09 17:42

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200518_2156'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='blog_image',
            field=models.FileField(blank=True, null=True, upload_to=blog.models._save_blog_upload_image_files),
        ),
    ]
