# Generated by Django 3.0.7 on 2020-07-10 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20200710_1846'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='blog_image',
            new_name='blog_banner_image',
        ),
        migrations.AddField(
            model_name='blog',
            name='blog_thumbnail',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=''),
        ),
    ]
